use_frameworks!

platform :ios, '9.0'

target 'MyOtherPodss_Example' do
  pod 'MyOtherPodss', :path => '../'

  target 'MyOtherPodss_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
